datasources:
  - id: 1
    uid: edhtvgjt7mewwc
    orgId: 1
    name: marcusolsson-csv-datasource
    type: marcusolsson-csv-datasource
    typeName: CSV
    typeLogoUrl: public/plugins/marcusolsson-csv-datasource/img/logo.svg
    access: proxy
    url: "/data/descriptive_analysis.csv"
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData:
      storage: local
    readOnly: false
