apiVersion: 1

datasources:
  - name: CSV
    type: marcusolsson-csv-datasource
    access: proxy
    url: "/data/descriptive_analysis.csv"
    isDefault: true
    basicAuth: false
    editable: true
    jsonData:
      storage: "local"

