apiVersion: 1

datasources:
  - name: CSV-holt_winter_last_test
    type: marcusolsson-csv-datasource
    access: proxy
    url: "/data/holt_winter/latest.csv"
    isDefault: false
    basicAuth: false
    editable: true
    jsonData:
      storage: "local"
