apiVersion: 1

datasources:
  - name: CSV-latest-sarima
    type: marcusolsson-csv-datasource
    access: proxy
    url: "/data/latest_sarima.csv"
    isDefault: false
    basicAuth: false
    editable: true
    jsonData:
      storage: "local"
