apiVersion: 1

datasources:
  - name: CSV-latest-random-forest
    type: marcusolsson-csv-datasource
    access: proxy
    url: "/data/latest-random-forest.csv"
    isDefault: false
    basicAuth: false
    editable: true
    jsonData:
      storage: "local"
