apiVersion: 1

datasources:
  - name: CSV-latest_history
    type: marcusolsson-csv-datasource
    access: proxy
    url: "/data/latest_history.csv"
    isDefault: false
    basicAuth: false
    editable: true
    jsonData:
      storage: "local"
