apiVersion: 1

datasources:
  - name: CSV-random_forest_last_test
    type: marcusolsson-csv-datasource
    access: proxy
    url: "/data/random_forest/latest.csv"
    isDefault: false
    basicAuth: false
    editable: true
    jsonData:
      storage: "local"
